aws-s3-bucket.yml
docs/draft-release-notes.md
terraform/s3/provision/main.tf
terraform/s3/provision/variables.tf

By default versioning is disabled, but can be enabled in plan configuration or during service instance creation.
Update of the versioning is prohibited since we are not sure of the side effects.

feat: s3 bucket supports versioning

---

aws-redis-cluster.yml

Medium and Large have incorrect HA word in the display name

fix: Update display names for Redis

---

aws-mysql.yml
aws-postgresql.yml
docs/draft-release-notes.md

fix: minimum constraint on storage_gb for MySQL and PostgreSQL

---

Makefile

- new check only prints when there is an error
- new check does not allow substring matches
[#181960182](https://www.pivotaltracker.com/story/show/181960182)

chore: improve Go version check

---

acceptance-tests/helpers/services/create.go

Tests that don't use the default broker should not fail when the default
broker is not deployed
[#182413672](https://www.pivotaltracker.com/story/show/182413672)

test: allow runs without default broker

---

aws-s3-bucket.yml
docs/draft-release-notes.md
integration-tests/s3_test.go

s3 bucket region cannot be changed, this will result in faster
feedback and better error message
[#182259915](https://www.pivotaltracker.com/story/show/182259915)

feat: prevent region update for s3

---

aws-s3-bucket.yml
docs/aws-installation.md
docs/draft-release-notes.md
integration-tests/s3_test.go
terraform/s3/provision/main.tf
terraform/s3/provision/variables.tf

This allows plans to be defined with bucket ownership controls
or if not defined in the plan, the value can be set at provision
or update.
[#182479512](https://www.pivotaltracker.com/story/show/182479512)

feat: s3 bucket ownership controls can now be set

---

aws-s3-bucket.yml
integration-tests/s3_test.go

Whilst the recommended setting is BucketOwnerEnforced
this causes updates to ACL to fail. We should match the console
default of ObjectWriter.
[#182479512](https://www.pivotaltracker.com/story/show/182479512)

fix: boc match the default value to aws console

---

aws-s3-bucket.yml
docs/draft-release-notes.md
integration-tests/s3_test.go
terraform/s3/provision/main.tf
terraform/s3/provision/variables.tf

This allows the server_side_encryption resource to be created
if a user specifies in a plan/provision request.
[#182296596](https://www.pivotaltracker.com/story/show/182296596)

feat: s3 allow server side encryption to be configured

---

acceptance-tests/apps/postgresqlapp/internal/app/app.go
docs/draft-release-notes.md
go.mod
terraform/postgresql/bind/provider.tf

- AWS enables TLS on PostgreSQL databases
- The Terraform provider that creates bindings should therefore protect
against "machine in the middle" attacks by validating the CA
- This will require the AWS certificate bundle to have been installed,
but it's a fair bet that folks do this anyway.
- acceptance tests have also been updated to verify TLS via the CA
[#182758757](https://www.pivotaltracker.com/story/show/182758757)

feat: "verify-ca" when connecting to PostgreSQL database

---

aws-postgresql.yml
docs/draft-release-notes.md
terraform/postgresql/bind/outputs.tf
terraform/postgresql/bind/variables.tf
terraform/postgresql/provision/data.tf
terraform/postgresql/provision/main.tf
terraform/postgresql/provision/outputs.tf
terraform/postgresql/provision/variables.tf

The "use_tls" parameter has been renamed to "require_ssl" and when true
(default) it will configure the server to require an SSL connection. It
can be set to false, in which case the server will accept SSL or
non-SSL connections. If "parameter_group_name" is specified then it will
not take effect.
[#182758757](https://www.pivotaltracker.com/story/show/182758757)

feat: server should reject non-TLS connections by default

---

acceptance-tests/helpers/brokers/env.go
acceptance-tests/upgrade/update_and_upgrade_s3_test.go
aws-s3-bucket.yml
integration-tests/s3_test.go

AWS suggest using BucketOwnerEnforced for ownership controls,
we had to amend the value updated in the tests as ACLs are
disabled through the use of this value.
[#182479512](https://www.pivotaltracker.com/story/show/182479512)

feat: amend default value to align with AWS reccomended

---

acceptance-tests/helpers/brokers/env.go

The plan set in the test is different to the plan set in the Makefile
and the push-broker.sh script
[#182296536](https://www.pivotaltracker.com/story/show/182296536)

test(s3): update plan to be consistent

---

aws-s3-bucket.yml
integration-tests/s3_test.go
terraform/s3/provision/main.tf

This relates to the properties:
- sse_default_kms_master_key_id
- sse_default_algorithm
These are string values and can be set. When trying to unset them, there
has been some debate as to whether they should be set to "null" or
whether they should be set to the empty string "". Since the
introduction of a new feature allowing strings to be nullable, we have
decided that the best way to unset these properties is to set them to
"null". This change marks the fields as nullable, and mostly reverts PR #388
See: https://github.com/cloudfoundry/cloud-service-broker/pull/584
[#182296596](https://www.pivotaltracker.com/story/show/182296596)

feat: allow s3 encryption value to set to null

---

aws-postgresql.yml
integration-tests/postgresql_test.go

Plan version change was not backwards compatible

fix: Keep Postgres version to 11 for all existing plans

---

acceptance-tests/helpers/brokers/create.go
acceptance-tests/helpers/brokers/env.go
acceptance-tests/helpers/brokers/update.go
acceptance-tests/upgrade/README.md
docs/draft-release-notes.md
manifest.yml

This enables a basic Terraform upgrade so that the upgrade tests will
behave correctly and update HCL. In a future change we will update the
upgrade path to take it to a much more recent version.
[#182855842](https://www.pivotaltracker.com/story/show/182855842)

feat: enable Terraform upgrades

---

aws-postgresql.yml
docs/draft-release-notes.md

Cores are a translation layer to the `instance_class` property. Added recommendation to use instance_class
[#182854680](https://www.pivotaltracker.com/story/show/182854680)

feat: Deprecate cores and make them not required

---

Makefile
acceptance-tests/helpers/brokers/env.go
scripts/push-broker.sh

The default plan needs to have a storage size of 100GB due
to the storage type being `io1`.
[#182758641](https://www.pivotaltracker.com/story/show/182758641)

test: amend default Postgresql plan to work

---

aws-postgresql.yml

In older versions of the MySQL and PostgreSQL services, the same provision file was shared. The engine property was a computed property that is now defined in the data file.
[#183075092](https://www.pivotaltracker.com/story/show/183075092)

chore: Remove unused computed property engine

---

aws-postgresql.yml
docs/draft-release-notes.md
integration-tests/postgresql_test.go

Updating the db_name property results in a destructive
action as the db is recreated by Terraform.
This change fails the update quickly for improved user
experience.

feat: db_name no update

---

dependency-manifest.yml

Our Norsk tooling is failing to scan certain packages
due to requiring a more recent version of Go. This change
in addition to an amend in the Norsk config should allow
scanning to take place.
[#183138382](https://www.pivotaltracker.com/story/show/183138382)
Signed-off-by: Marcela Campo <mcampo@vmware.com>

chore: amend dependency-manifest to fix Norsk

---

acceptance-tests/apps/s3app/internal/credentials/credentials.go
acceptance-tests/s3_migration_test.go

Test validates that the `aws s3 sync` command can be used to migrate S3 instances from the old broker to the new broker.
[#182845406](https://www.pivotaltracker.com/story/show/182845406)

test: Add test for s3 migration from legacy

---

acceptance-tests/helpers/brokers/env.go

Env vars from latest release are promoted to default env vars

test: Promote latest env var

---

terraform-tests/README.md
terraform-tests/mysql_test.go
terraform-tests/postgres_test.go

~~*[ ] Have you added Release Notes in the docs repositories?~~

test(terraform): tidy up mysql terraform tests

---

aws-mysql.yml
aws-postgresql.yml
integration-tests/mysql_test.go
integration-tests/postgresql_test.go

changing storage encrypted will trigger a recreate. We wan't to avoid recreating service instances as much as possible.
update tests to check for the param being not changeable anymore.
[#179839584]

feat: storage encrypted shouldn't be changed

---

aws-aurora-mysql.yml
integration-tests/aurora_mysql_test.go
terraform-tests/aurora_mysql_test.go
terraform/aurora-mysql/provision/data.tf
terraform/aurora-mysql/provision/main.tf
terraform/aurora-mysql/provision/variables.tf
terraform/mysql/provision/main.tf

By setting "serverless_min_capacity" and "serverless_max_capacity" a user can create a cluster in serverless mode (perhaps better called autoscaling mode). It's necessary to set "engine_version" to a version that supports serverless.
[#183390182](https://www.pivotaltracker.com/story/show/183390182)

feat: Aurora MySQL enable serverless

---

aws-aurora-postgresql.yml
integration-tests/aurora_postgresql_test.go
terraform-tests/aurora_postgresql_test.go
terraform/aurora-postgresql/provision/main.tf
terraform/aurora-postgresql/provision/variables.tf

aws_rds_cluster and aws_rds_cluster_instance are tagged with the default pcf tags
[#183567562](https://www.pivotaltracker.com/story/show/183567562)

feat: aurora-pgsql- Add default tags

---

aws-aurora-postgresql.yml
terraform-tests/aurora_postgresql_test.go
terraform/aurora-postgresql/provision/main.tf
terraform/aurora-postgresql/provision/variables.tf

[#183474202](https://www.pivotaltracker.com/story/show/183474202)

feat: Automated backups for Aurora PostgreSQL

---

acceptance-tests/aurora_mysql_test.go
terraform/aurora-mysql/bind/main.tf
terraform/aurora-mysql/bind/outputs.tf
terraform/aurora-mysql/bind/provider.tf
terraform/aurora-mysql/bind/versions.tf

Using the new TF provider, by default, all users will connect using TLS due to the configuration per-account level.
[#183650281](https://www.pivotaltracker.com/story/show/183650281)

feat: Aurora MySQL TLS connections always enabled

---

aws-aurora-mysql.yml
aws-aurora-postgresql.yml
aws-mysql.yml
aws-postgresql.yml
integration-tests/aurora_mysql_test.go
integration-tests/aurora_postgresql_test.go
integration-tests/mysql_test.go
integration-tests/postgresql_test.go

When updated it triggers a DependencyViolation error.
[#183701503](https://www.pivotaltracker.com/story/show/183701503)

fix: Make rds_vpc_security_group_ids not updatable

---

acceptance-tests/helpers/brokers/env.go

After latest rc release the latest env vars are turned into default vars

test: Move latest to default env vars

---

aws-aurora-mysql.yml
integration-tests/aurora_mysql_test.go
terraform-tests/aurora_mysql_test.go
terraform/aurora-mysql/provision/main.tf
terraform/aurora-mysql/provision/variables.tf

[#183556418](https://www.pivotaltracker.com/story/show/183556418)

feat: Aurora MySQL Enabling Advanced Auditing logging

---

aws-redis-cluster.yml
terraform-tests/redis_test.go
terraform/redis/cluster/provision/data.tf
terraform/redis/cluster/provision/main.tf

The version was not being used to set the engine and it was relying on the default AWS. The engine was used to create the parameter group name. Now the version is used correctly to select the engine version and the parameter group name is not set as the default will be correct and based on the engine version.
[#183758518](https://www.pivotaltracker.com/story/show/183758518)

fix: Redis- Removed limitation of redis version

---

terraform/aurora-postgresql/provision/main.tf

The default Aurora Postgres cluster group parameter name is an autogenerated TF name that doesn't link back to the instance easily. E.g. terraform-20221103164025814000000001
[#183710093](https://www.pivotaltracker.com/story/show/183710093)

fix: Set a name for the Aurora pgsql cluster_parameter_group

---

manifest.yml

Initialising the AWS provider is failing more frequently. 
It looks like this started happening after the provider was upgraded to 1.48.0
Temporarily reverting back to 1.37.0 to see if this is related. 
[#183791703](https://www.pivotaltracker.com/story/show/183791703)

chore: Revert aws provider bump

---

dependency-manifest.yml
manifest.yml

Provider bump is causing errors during instantiation of the AWS provider. Reverting for the moment until we investigate the issue with the error: Error: Failed to load plugin schemas Error while loading schemas for plugin components: Failed to obtain provider schema: Could not load the schema for provider registry.terraform.io/hashicorp/aws: failed to instantiate provider "registry.terraform.io/hashicorp/aws" to obtain schema: timeout while waiting for plugin to start.
[#183791703](https://www.pivotaltracker.com/story/show/183791703)

chore: Revert aws provider bumps

---

acceptance-tests/aurora_mysql_data_migration_test.go
acceptance-tests/helpers/dms/endpoint.go
acceptance-tests/mysql_data_migration_test.go
acceptance-tests/postgresql_data_migration_test.go

- tests create DMS endpoints
- this adds the environment name as a prefix to the generated name
- allows us to tell which endpoints are associated with which environment
- includes a refactor to use named parameters when creating endpoint
[#183934867](https://www.pivotaltracker.com/story/show/183934867)

test: mark DMS endpoints with environment name

---

integration-tests/aurora_mysql_test.go
integration-tests/aurora_postgresql_test.go
integration-tests/dynamodb_test.go
integration-tests/integration_test_suite_test.go
integration-tests/mysql_test.go
integration-tests/postgresql_test.go
integration-tests/redis_test.go
integration-tests/s3_test.go

The integration tests contained a lot of:
```
Expect(foo).ToNot(BeNil())
```
which for a string value can never fail. These tests have been improved to match against expected data.

test: improve matching in integration tests

---

acceptance-tests/helpers/apps/prebuild.go

In the GCP brokerpak we increased the timeout for test app prebuild to 5 minutes, and it reduced test flakes. In order to fix similar flakes, we should increase the timeout in this brokerpak too.

test: increase pre-build timeout to match GCP

---

cf-manifest.yml

Acceptance tests are faling due to no space left in device. We need to further investigate the reason, and revert this commit if we can avoid increase the disk space needed in some way.
[#184401283](https://www.pivotaltracker.com/story/show/184401283)

chore: Increase cf manifest disk quota

---

aws-redis-cluster.yml

[#184405164](https://www.pivotaltracker.com/story/show/184405164)
After removing built-in plans an "example" plan was created and is used to run every example. But this plan specifies the node_count parameter so it can't be modified at provisioning level.
I have decided to delete the example to not saturate the marketplace and CI pipeles with several example plans with different configurations for the same service.

fix: remove failing example after removing plans

---

Makefile
README.md

[#184641527](https://www.pivotaltracker.com/story/show/184641527)

chore: use new run-example method in Makefile

---

.envrc
acceptance-tests/helpers/brokers/env.go
acceptance-tests/upgrade/update_and_upgrade_redis_test.go

The default value for node_count is 2, so there's no need to explicitly set it in any plans
[#184651843](https://www.pivotaltracker.com/story/show/184651843)

chore: remove node_count from plans

---

aws-aurora-mysql.yml
aws-aurora-postgresql.yml
aws-mysql.yml
aws-postgresql.yml

[#184613881](https://www.pivotaltracker.com/story/show/184613881)

chore: fix some property types

---

aws-redis.yml

This is because the default vpc may have only 1 availability zone and they fail.
[#184471692](https://www.pivotaltracker.com/story/show/184471692)

test(redis): redis example tests should run with multiAZ off

---

aws-dynamodb-namespace.yml
manifest.yml
terraform-tests/dynamodb_namespace_test.go
terraform/dynamodb-namespace/provision/outputs.tf
terraform/dynamodb-namespace/provision/variables.tf

[#184673495](https://www.pivotaltracker.com/story/show/184673495)

feat: Initial dynamodb-ns implementation

---

acceptance-tests/apps/postgresqlapp/go.mod
acceptance-tests/apps/postgresqlapp/go.sum
acceptance-tests/apps/postgresqlapp/internal/app/app.go
acceptance-tests/apps/postgresqlapp/internal/app/create_schema.go
acceptance-tests/apps/postgresqlapp/internal/app/drop_schema.go
acceptance-tests/apps/postgresqlapp/internal/app/get.go
acceptance-tests/apps/postgresqlapp/internal/app/set.go

gorilla/mux has been archived and subsequently removed from most test apps. The postgresql test app is sufficiently complex that a framework is needed in addition to the standard "net/http" package.
chi was chosen because of it plays well with "net/http" and has been the replacement for gorilla/mux in a number of other CloudFoundry projects
[#184006000](https://www.pivotaltracker.com/story/show/184006000)

test: replace gorilla/mux with chi in test app

---

aws-dynamodb-namespace.yml
integration-tests/aurora_mysql_test.go
integration-tests/aurora_postgresql_test.go
integration-tests/dynamodb_namespace_test.go
integration-tests/integration_test_suite_test.go
integration-tests/mysql_test.go
integration-tests/postgresql_test.go
integration-tests/redis_test.go
integration-tests/s3_test.go
terraform-tests/dynamodb_namespace_test.go

To make it easier to read table names, the dynamodb prefix has been updated from "csb-GUID" to "csb-GUID-" so that table names will be of the form "csb-GUID-example_table" and it will be easier to distinguish between the prefix and the table name.
[#184866266](https://www.pivotaltracker.com/story/show/184866266)

feat(dynamodb): add separator at end of prefix

---

acceptance-tests/helpers/brokers/env.go

We need the renaming of TF in the acceptance tests. The acceptance tests do not read the full .envrc file, only the service plans.
[#184670887](https://www.pivotaltracker.com/story/show/184670887)

fix: add environment variable to execute TF upgrade

---

providers/terraform-provider-csbdynamodbns/resource_dynamodb_instance_test.go

Downloading the Docker images was usually taking longer than the specified timeout. We run docker pull with a different session to overcome this issue.

test: avoid timeout in DynamoDB

---

terraform-tests/redis_test.go

[#185273812]
availability_zones has been deprecated for some time in latest version of the aws terraform provider this property has been removed.
It doesn't impact the service in any way. Tests were failing because we were proactively checking for any possible changes in all properties (even the ones we are not using).

fix: [AWS] removed prop in Terraform Redis resource

---

acceptance-tests/helpers/dms/endpoint.go

test.
aws cli has issues with argument parsing with arguments with leading dashes
this change implements workaround proposed here https://github.com/aws/aws-cli/issues/1135#issuecomment-77254897
[#185541709](https://www.pivotaltracker.com/story/show/185541709)
~~ * [ ] Have you added Release Notes in the docs repositories?~~

chore: workaround issue with passwords with leading dashes in migration

---

acceptance-tests/dynamodb_namespace_data_migration_test.go
acceptance-tests/dynamodb_table_test.go
acceptance-tests/helpers/apps/app.go
acceptance-tests/helpers/apps/push.go
acceptance-tests/upgrade/update_and_upgrade_aurora_mysql_test.go
acceptance-tests/upgrade/update_and_upgrade_aurora_postgresql_test.go
acceptance-tests/upgrade/update_and_upgrade_dynamodb_table_test.go
acceptance-tests/upgrade/update_and_upgrade_mysql_test.go
acceptance-tests/upgrade/update_and_upgrade_postgresql_test.go
acceptance-tests/upgrade/update_and_upgrade_s3_test.go

This reverts commit ab94c6b46eff54511574a4a7fb1f94fcf934ecdf.
Reason for `insufficient disk` error was total diego cell available disk and not specific apps needing more space. We increased compute instance size in our pool for now. We'll try to reduce the amount of disk needed in future improvements.
[#185528524]

chore: Revert "chore: insufficient "disk" in acceptance tests (#990)"

---

aws-mssql.yml
integration-tests/mssql_test.go

[#185286271]
Current constraints according to the AWS Web Console are:
- Must be 63 characters or less.
- Must start with a letter (A-Z and a-z)
- Must contain only letters, numbers and hyphens.
- Must not have two consecutive hyphens
- Must not have a hyphen at the end.

fix: [MSSQL] fix instance_name constraints

---

terraform-tests/mssql_test.go

[#185149632]
When no kms_key_id is provided or an empty string is provided   no value for kms_key_id is sent to terraform. Test was wrong.

fix: [MSSQL] with defaults kms_key_id is null

---

aws-mssql.yml
integration-tests/mssql_test.go
terraform-tests/mssql_test.go
terraform/mssql/provision/main.tf
terraform/mssql/provision/variables.tf

[#185149499]
This implementation doesn't follow conventions stablished in mysql or postgresql on how to expose storage autoscale.
A larger discussion of the reasons can be found in the tracker story. The summary is we no longer need to.
We can now define nullable numbers which were impossible before we can also use Terraform preconditions to validate inputs, etc

feat: [MSSQL] expose support for storage autoscale

---

aws-mssql.yml

[#185149499]
- We made the field nullable yet the default is 0 and docs say we need to set to 0 to disable. This means it doesn't need to be nullable.
- In previous discussions around this kind of interface, the team agreed that a 0 value, although in use by the provider and probably by the API, it is not as intuitive as null, hence preferred way to implement would be to set to null by default and instruct the user to set to null to disable, whilst treating null as 0 when passing it to terraform.

fix: [MSSQL] eliminate the default and go for nullable

---

Makefile

Existing targets run all terraform or integrations tests for all services unless you use FIt, FDescribe, FWhen, etc to limit them.
This new Makefile uses git to detect which files were modified and pass them to ginkgo through the `--focus-file`. This in effect causes Ginkgo to ignore any other tests files in the project.
Warning: This target doesn't try to be smart and automatically run any tests related to some modified non-test file. The only thing this target does is run any test files modified in the current branch.

chore: add make target to run only modified tests

---

acceptance-tests/helpers/brokers/manifest.go
cf-manifest.yml

our tests.
We are currently using a compute VM with 16G, so this change should also increase cpu share for each broker
[#186060164](https://www.pivotaltracker.com/story/show/186060164)
~~* [ ] Have you ran `make run-integration-tests` and `make run-terraform-tests`?~~
~~* [ ] Have you ran acceptance tests for the service under change?~~

chore: attempt to use more memory and processor for each broker

---

aws-mssql.yml
integration-tests/mssql_test.go

The engine modification causes the recreation of the instance.
[#186142807](https://www.pivotaltracker.com/story/show/186142807)

fix: engine should not be updateable

---

providers/terraform-provider-csbsqlserver/connector/connector.go
providers/terraform-provider-csbsqlserver/csbsqlserver/binding_resource_test.go

with azure provider
- master.dbo.sysdatabases in not accessible in azure. However the system view sys.databases is and also works fine in AWS. So opting to use that system view to decide if the database already exists.
[#185100152](https://www.pivotaltracker.com/story/show/185100152)

chore: backporting query change for mssql provider to keep alignment

---

acceptance-tests/mssql_data_migration_test.go
acceptance-tests/mssql_test.go
providers/terraform-provider-csbsqlserver/connector/connector_test.go

[#185100152](https://www.pivotaltracker.com/story/show/185100152)
Mssql's example app created SCHEMAs passing AUTHORIZATION dbo This caused the schema to be assigned to dbo at creation time causing the unbinding issue to pass unnoticed

fix: [MSSQL] make tests detect unbinding issue

---

acceptance-tests/helpers/dms/task.go
acceptance-tests/mysql_data_migration_test.go

The database migration test started to fail because it could not copy across the "performance_insights" schema. This was likely triggered by a change in AWS, but the underlying cause is that the migration test tries to copy across all schemas, and we should restrict it to just copying across the data schema.
[#186350212](https://www.pivotaltracker.com/story/show/186350212)

test: only migrate data schema

---

dependency-manifest.yml
manifest.yml

fix: incorrect prerelease version used as latest

---

manifest.yml

Adds Terraform 1.5.7
- At this stage Terraform 1.6 is not being added as it has a different license
- The question was raised as to whether we are shipping more Terraform versions than we need. Story [#186436578](https://www.pivotaltracker.com/story/show/186436578) has been created to look into this.
[#185536344](https://www.pivotaltracker.com/story/show/185536344)

feat: add Terraform 1.5

---

aws-redis.yml
terraform/redis/cluster/binding/variables.tf

[#183286656](https://www.pivotaltracker.com/story/show/183286656)

fix: [Redis] use integer type in tls_port property

---

providers/terraform-provider-csbmajorengineversion/csbmajorengineversion/datasource_majorengineversion_test.go
terraform-tests/aurora_mysql_test.go

chore: replace mysql version not supported in GovCloud

---

aws-postgresql.yml

Runway connectivity issues exist in binding operation. Reviewing the other PostgreSQL services we have noticed that we use the bind_can_fail flag. For consistency we assign the same configuration to the test and postpone the decision to solve the connectivity problems associated with Runway
[#186332128](https://www.pivotaltracker.com/story/show/186332128)

fix: runway connectivity issues in binding operation

---

acceptance-tests/mssql_test.go

Each test is quite slow, and if we give them different labels then it's easier to run them separately in parallel
Note, merge https://github.com/pivotal/cloud-service-broker-ci/pull/637 too
[#186494970](https://www.pivotaltracker.com/story/show/186494970)

test: separate out the MS-SQL tests

---

acceptance-tests/apps/s3app/internal/app/upload.go
acceptance-tests/apps/s3app/internal/app/upload_with_acl.go

Looks like there have been some Go type changes in the AWS library, presumably introduced in #1304. This changes the test app to match the library.

test: update test app for AWS lib change

---

.github/dependabot.yml

- we previously switched to weekly to reduce the quantity of PRs
- we want to see whether we can now cope with daily updates

chore: experiment with daily Dependabot updates

---

manifest.yml

An issue was discovered in the AWS terraform provider v5.30.0: https://github.com/hashicorp/terraform-provider-aws/pull/34812
This reverts commit 03360669adc35de2938b5100b274ce1f7c2ed7f2.
[#186655365](https://www.pivotaltracker.com/story/show/186655365)

revert: "build(deps): bump terraform providers"

---

manifest.yml
terraform/mysql/bind/provider.tf
terraform/postgresql/bind/provider.tf

In order to reduce the size of the brokerpak, obsolete Terraform providers have been removed. As a result, to get to this version through upgrading, you must upgrade to v1.10 first and upgrade all service instances to v1.10. This can be done via "cf upgrade-service", or for bulk upgrades consider the plugin: https://github.com/cloudfoundry/upgrade-all-services-cli-plugin You can then upgrade to this version, and again upgrade all the service instances.
[#186588913](https://www.pivotaltracker.com/story/show/186588913)

feat: restrict upgrade to v1.10 only

---

acceptance-tests/mssql_data_migration_test.go

Fixes an issue introduced in:
- https://github.com/cloudfoundry/csb-brokerpak-aws/pull/1451
Failing pipeline:
- https://runway-ci.eng.vmware.com/teams/service-enablement/pipelines/aws-csb/jobs/cf-test/builds/226#L658206ee:236

fix: disable encryption since it's unsupported for db.t3.micro

---

acceptance-tests/upgrade/update_and_upgrade_aurora_postgresql_test.go

Complements PR:
- https://github.com/cloudfoundry/csb-brokerpak-aws/pull/1483

fix: disable auto_minor_version_upgrade

---

acceptance-tests/upgrade/update_and_upgrade_aurora_postgresql_test.go

changed to increase capacity on serverless instance instead of doing extra updates to change instance class. aurora seems to be particularly problematic by itself on upgrades, even through the console.
In this test we want to test that the brokerpak has been changed in a way that allows for updates and upgrades and not aws behavior.
[#186886707](https://www.pivotaltracker.com/story/show/186886707)
~~* [ ] Have you ran `make run-integration-tests` and `make run-terraform-tests`?~~

test(acceptance): simplify aurora-postgres update and upgrade test

---

Makefile
README.md
providers/terraform-provider-csbdynamodbns/Makefile
providers/terraform-provider-csbmajorengineversion/Makefile

The same benefits can be achieved by simply launching an interactive docker session inside a supported image and running commands from there. This approach has some additional benefits
- Easier to maintain
- Debloats Makefile
- Less hidden magic
- Same code for local and containerised execution

chore: remove run-in-docker logic from Makefile

---

acceptance-tests/apps/dynamodbnsapp/go.mod
acceptance-tests/apps/dynamodbtableapp/go.mod
acceptance-tests/apps/mssqlapp/go.mod
acceptance-tests/apps/mysqlapp/go.mod
acceptance-tests/apps/postgresqlapp/go.mod
acceptance-tests/apps/redisapp/go.mod
acceptance-tests/apps/s3app/go.mod
go.mod
providers/terraform-provider-csbdynamodbns/go.mod
providers/terraform-provider-csbmajorengineversion/go.mod

Related PRs:
- https://github.com/pivotal/cloud-service-broker-ci/pull/795

chore: specify go 1.22.0 in go.mod

---

aws-sqs.yml
terraform/sqs/provision/outputs.tf

Renames some SQS field names to have the same name as is used in the legacy AWS broker. This will maximise compatibility.
[#186787985](https://www.pivotaltracker.com/story/show/186787985)

feat: align SQS binding field names with legacy broker

---

Makefile
providers/terraform-provider-csbdynamodbns/Makefile
providers/terraform-provider-csbmajorengineversion/Makefile

[#187027977](https://www.pivotaltracker.com/story/show/187027977)
Before Go 1.21:
- The go directive was advisory only; now it is a mandatory requirement
- The go directive didn't allow specifying patch versions
So, by specifying the patch version in go.mod:
- Noone can unknowingly test, run or build this project using an older version of go
- The required Go toolchain can be downloaded automatically
Therefore, checking the current go version in Makefile is no longer needed.

chore: stop checking go version in Makefile

---

aws-sqs.yml
integration-tests/sqs_test.go
terraform/sqs/bind/data.tf
terraform/sqs/bind/main.tf
terraform/sqs/bind/outputs.tf
terraform/sqs/bind/provider.tf
terraform/sqs/bind/variables.tf
terraform/sqs/bind/versions.tf

- Introduces bindings for SQS
- A binding is a IAM User with a key/secret and a policy
- Using an AWS key/secret is no longer considered the best way to give access to an AWS resource. However it is the way that the legacy broker gives access, so for maximum compatibility it makes sense to do the same. A more modern approach would be to use IAM Roles Anywhere. But using that would likely involve big changes to existing apps, and we are currently trying to prioritise compatibility over modernity.
- The policy for an SQS queue is hard-coded and minimal. It gives less permissions that the legacy broker did, and we will need to add more permissions for DLQs. The aim is that for an action that a user should do via the broker (e.g. delete the queue), that permission is not accessible via a …

feat: bindings for SQS (experimental)

---

scripts/push-broker.sh

Previously we would always try and create the broker, and if that failed (for any reason) then attempt to update it. This resulted in output that sometimes confused users.

chore: use --update-if-exists flag when pushing broker

---

aws-sqs.yml
integration-tests/sqs_test.go
terraform-tests/sqs_test.go
terraform/sqs/provision/main.tf
terraform/sqs/provision/variables.tf

[#186768799](https://www.pivotaltracker.com/story/show/186768799)

feat: first basic version of DLQ

---

aws-sqs.yml
integration-tests/sqs_test.go
terraform-tests/sqs_test.go
terraform/sqs/provision/main.tf
terraform/sqs/provision/variables.tf

feat: Added config for visibility_timeout_seconds

---

terraform-tests/mssql_test.go

[#187103734](https://www.pivotaltracker.com/story/show/187103734)
Recently, a new PR for validating this property was merged: https://github.com/hashicorp/terraform-provider-aws/pull/35870
I believe it's valuable to have our tests break when changes like this are introduced in the providers. Therefore, we should try have behaviours such as this encoded in our tests. Things like: "invalid values for property X are not validated by TF".

fix: aws terraform-tests performance_insights_retention_period

---

aws-sqs.yml
terraform-tests/sqs_test.go

`deduplication_scope` and `fifo_throughput_limit` do not apply for standard queues and they will throw error if attempted to be set (e.g. because there is a default)

fix: Fifo properties should only be set if the queue is of type FIFO

---

terraform-tests/sqs_test.go

[#187061563](https://www.pivotaltracker.com/story/show/187061563)
Related PRs:
- https://github.com/cloudfoundry/csb-brokerpak-aws/pull/1600
By adding this test, if such validation ever gets implemented in the provider we'll know it since the test will start failing as happened for:
https://github.com/cloudfoundry/csb-brokerpak-aws/pull/1597

fix: test fifo properties are validated by the IAAS not TF

---

aws-mysql.yml
aws-postgresql.yml
integration-tests/mysql_test.go
integration-tests/postgresql_test.go

When creating rds instances an iops value of 0 is interpreted by downstream services as null value. However when updating this is not the case. Hence when trying to update a service where setting iops is not permitted by AWS, update operations error even when we are not trying to change the iops value. Allowing nulls for this property works as expected both for provisioning and update.
[#187149548](https://www.pivotaltracker.com/story/show/187149548)

fix: allow null values for iops

---

acceptance-tests/sqs_test.go

Reverts cloudfoundry/csb-brokerpak-aws#1638 since it caused tests to fail

Revert "test: Change test to check the FIFO queue"

---

terraform/aurora-mysql/bind/variables.tf
terraform/aurora-postgresql/bind/variables.tf
terraform/mssql/bind/variables.tf
terraform/mysql/bind/variables.tf
terraform/postgresql/bind/variables.tf

By annotating terraform variables that contain sensitive information, we ensure that they are not printed out in error messages.
[#183474478](https://www.pivotaltracker.com/story/show/183474478)

chore: annotate sensitive terraform varaibles

---

.github/dependabot.yml

The idea from this change came from the following slack thread: https://vmware.slack.com/archives/C5F98SBK8/p1709723670942369
Using a very permissive wildcard such as *aws-sdk-go-v2* could cause Dependabot to group version bumps for totally unrelated go modules/packages such as:
https://github.com/search?q=path%3Ago.mod+%28%22aws-sdk-go-v2%22+AND+NOT+%22github.com%2Faws%2Faws-sdk-go-v2%22%29&type=code
As of today, go.sum doesn't include any module named like that. However, new indirect dependencies can creep into our code which can match this wildcard.
Even in that scenario, I believe Dependabot doesn't bump indirect dependencies.
Still, I believe using more restrictive patterns is a better practice,  since it is easier to reason about and maybe a little bit safer.

chore: use more restrictive dependabot group patterns

---

aws-sqs.yml
terraform-tests/sqs_test.go
terraform/sqs/provision/main.tf

Allows the "sqs_managed_sse_enabled" to be disabled on a queue, while retaining the default of being enabled.
When "kms_master_key_id" is set, it will have the effect of unsetting "sqs_managed_sse_enabled", rather than failing with a conflict. This is to make the experience of setting "kms_master_key_id" more user-friendly.
[#187061621](https://www.pivotaltracker.com/story/show/187061621)

feat: SQS allow sqs_managed_sse_enabled to be disabled

---

.github/labeler.yml
.github/release.yml
.github/workflows/labeler.yml

Each PR will be labeled depending on the name of the branch according to convertional commits. The release notes will be clasified based on the type of PRs.

chore: Add labeler to improve the release notes.

---

terraform/s3/provision/main.tf

We have seen issues with the S3 provioning failing at timesbeccasue of bucket ACL issues. There are a few aticles refering to changes to the AWS provider that point out that the `s3_bucket_public_access_block` should be the first one to be created. 
See links: [1](https://github.com/hashicorp/terraform-provider-aws/issues/30951#issuecomment-1523376909) and [2](https://stackoverflow.com/questions/76419099/access-denied-when-creating-s3-bucket-acl-s3-policy-using-terraform)
[#187284776](https://www.pivotaltracker.com/story/show/187284776)

fix: S3 - Add dependency on aws_s3_bucket_public_access_block to reduce flakiness on provision

---

terraform/redis/cluster/provision/versions.tf

fix: Include random provider for redis

---

providers/terraform-provider-csbdynamodbns/go.mod
providers/terraform-provider-csbdynamodbns/go.sum
providers/terraform-provider-csbdynamodbns/resource_dynamodb_instance_test.go
providers/terraform-provider-csbdynamodbns/terraform_provider_dynamodbns_suite_test.go

A test was importing the cloud-service-broker app as a library. This has the downsides of:
- potentially breaking when internals of the app are changed
- creating an additional thing that needs updating
Since the imported function just requires a few lines of code, it's better to just duplicate the required function.
[#187499320](https://www.pivotaltracker.com/story/show/187499320)

test: don't import CSB as a library

---

terraform/s3/bind/data.tf

The permissions are now included in s3:PutReplicationConfiguration action.
See AWS docs: https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteBucketReplication.html
[#187476643](https://www.pivotaltracker.com/story/show/187476643)

fix: invalid s3:DeleteReplicationConfiguration policy

---

acceptance-tests/apps/mssqlapp/go.mod
acceptance-tests/apps/mssqlapp/go.sum
acceptance-tests/apps/mssqlapp/internal/app/app.go
acceptance-tests/apps/mssqlapp/internal/app/get.go
acceptance-tests/apps/mssqlapp/internal/app/set.go
acceptance-tests/apps/postgresqlapp/go.mod
acceptance-tests/apps/postgresqlapp/go.sum
acceptance-tests/apps/postgresqlapp/internal/app/app.go
acceptance-tests/apps/postgresqlapp/internal/app/get.go
acceptance-tests/apps/postgresqlapp/internal/app/set.go
acceptance-tests/apps/redisapp/go.mod
acceptance-tests/apps/redisapp/go.sum
acceptance-tests/apps/redisapp/internal/app/app.go
acceptance-tests/apps/redisapp/internal/app/get.go
acceptance-tests/apps/redisapp/internal/app/set.go

[#187470327](https://www.pivotaltracker.com/story/show/187470327)

chore: remove Chi from test apps

---

acceptance-tests/helpers/brokers/default.go

We want to run tests against the tile, so it's helpful if the tests can find the broker pushed by the tile.
[#187498188](https://www.pivotaltracker.com/story/show/187498188)

test: detect tile-pushed brokers

---

acceptance-tests/upgrade/update_and_upgrade_mysql_test.go

In a previous commit, the MySQL upgrade test was changed to no longer use a custom plan. This commit updates the plan name to match the one that is available once the custom plan has been removed.

test: correct plan name

---

manifest.yml

chore: Revert bumping tf aws provider until we consume latest bosh go release

---

aws-postgresql.yml
integration-tests/postgresql_test.go
terraform-tests/postgres_test.go
terraform/postgresql/provision/main.tf
terraform/postgresql/provision/variables.tf

Similar to MySQL this is required in order to be able to migrate instances from the legacy broker to CSB

feat: Enable passing admin username for Postgres

---

providers/terraform-provider-csbdynamodbns/Makefile
providers/terraform-provider-csbmajorengineversion/Makefile

GOARCH will default to arm64 rather than amd64

chore: build the right thing on M-series Mac

---

terraform-tests/redis_test.go

The underneath type of nullable boolean is a string

test: at_rest_encryption_enabled is a NullableBool

---

docs/configuration.md

docs: use ca_cert instead of ca_cert_file

---

acceptance-tests/helpers/services/delete.go
acceptance-tests/upgrade/update_and_upgrade_aurora_mysql_test.go
acceptance-tests/upgrade/update_and_upgrade_aurora_postgresql_test.go
acceptance-tests/upgrade/update_and_upgrade_mssql_test.go
acceptance-tests/upgrade/update_and_upgrade_mysql_test.go
acceptance-tests/upgrade/update_and_upgrade_postgresql_test.go
acceptance-tests/upgrade/update_and_upgrade_redis_test.go
acceptance-tests/upgrade/update_and_upgrade_s3_test.go
acceptance-tests/upgrade/update_and_upgrade_sqs_test.go
acceptance-tests/withoutcredhub_test.go

We can only have 5 instances of our test broker running. Tests that use the test broker can see 'failed to allocate' errors. This is because in the case of a failed creation of a service in our tests will fail to clean up the test broker, causing other test runs to fail.

chore: Fixes broker 'failed to allocate' test errors

---

acceptance-tests/mssql_test.go

Code previously could have added in MySQL security groups, which caused interference between tests

test: restore MS-SQL DB to MS-SQL security group

---

terraform/s3/bind/data.tf

The user for S3 bucket bindings will have the permission to tag objects within a bucket.
Behaviour verified manually. We don't add automated tests for every S3 behaviour.

feat: allow s3 objects to be tagged

---

Makefile
go.mod
tool/tools.go

- The cloud-service-broker dependency was updated to be a Go 1.24 tool
- This did not work because you can't "go build" a tool, it it's been reverted
- Also "make build" will now build the cloud-service-broker too, as this is typically used as the litmus test of whether everything is working, and in this case we had a miss.

chore: fix the cloud-service-broker build

---

acceptance-tests/aurora_postgresql_test.go

Aurora PG17 is no longer available. Updated test to test with v16.

chore: aurora postgres v17 is no longer available - test with v16

---

aws-aurora-mysql.yml
aws-aurora-postgresql.yml
aws-dynamodb-namespace.yml
aws-mssql.yml
aws-mysql.yml
aws-postgresql.yml
aws-redis.yml
aws-s3-bucket.yml
aws-sqs.yml
docs/README.md
integration-tests/integration_test_suite_test.go

Previous docs links results in an unhelpful redirect, while this new link goes to a more helpful place.

chore: update docs links

---

Makefile

In CI the tests take almost an hour, and occasionally a bit more - causing a failure

test: update terraform tests timeout

---

terraform-tests/redis_test.go

It seems that the aws_elasticache_replication_group resource no longer returns the engine type. This is likely to be an AWS API change as the provider version did not change. It has been stable for about 10 days, so we should update the test to match.

test: update for changed properties
