aws-dynamodb.yml

[#177397719](https://www.pivotaltracker.com/story/show/177397719)

chore: add dynamodb example test

---

Makefile
README.md

build: move cache directory outside of brokerpak dir

---

docs/configuration.md

[#181979576](https://www.pivotaltracker.com/story/show/181979576)

docs: update configuration docs

---

dependency-manifest.yml
manifest.yml
terraform/dynamodb/bind/provider.tf
terraform/dynamodb/provision/provider.tf
terraform/rds/provision/provider.tf
terraform/redis/cluster/provision/provider.tf
terraform/s3/bind/provider.tf
terraform/s3/provision/provider.tf

[#182285651](https://www.pivotaltracker.com/story/show/182285651)

chore: bump aws tf provider to 4.17.1

---

aws-s3-bucket.yml
docs/draft-release-notes.md
integration-tests/s3_test.go

This results in faster feedback and improved error messaging
[#182259845](https://www.pivotaltracker.com/story/show/182259845)

feat: s3 prevent bucket name updates

---

acceptance-tests/helpers/brokers/env.go

[#182285965](https://www.pivotaltracker.com/story/show/182285965)

test: change required flag for env variable in acceptance tests

---

aws-s3-bucket.yml
docs/draft-release-notes.md
integration-tests/s3_test.go

[#182297079](https://www.pivotaltracker.com/story/show/182297079)

feat: s3 - allow update of acl if plan does not set a value

---

terraform/mysql/provision/main.tf
terraform/postgresql/provision/main.tf
terraform/s3/provision/main.tf

[#182758769](https://www.pivotaltracker.com/story/show/182758769)

chore: use new "db_name" param in MySQL and PostgreSQL

---

terraform/s3/provision/main.tf

chore: Replace deprecated fields in S3

---

aws-dynamodb.yml
aws-mysql.yml
aws-postgresql.yml
aws-redis-cluster.yml
docs/draft-release-notes.md
integration-tests/dynamodb_test.go
integration-tests/mysql_test.go
integration-tests/postgresql_test.go
integration-tests/redis_test.go

[#182611145](https://www.pivotaltracker.com/story/show/182611145)

fix: add prohibit_update to the region

---

aws-postgresql.yml
docs/draft-release-notes.md
integration-tests/postgresql_test.go
terraform/postgresql/provision/main.tf
terraform/postgresql/provision/variables.tf
terraform/s3/provision/main.tf

[#182758638](https://www.pivotaltracker.com/story/show/182758638)

feat(postgresql): expose "deletion_protection" property

---

acceptance-tests/helpers/apps/testapps.go
acceptance-tests/helpers/services/create.go
acceptance-tests/helpers/services/delete.go
acceptance-tests/helpers/services/guid.go
acceptance-tests/helpers/services/services.go
acceptance-tests/helpers/services/update.go
acceptance-tests/helpers/services/upgrade.go
acceptance-tests/postgresql_test.go
acceptance-tests/upgrade/update_and_upgrade_postgres_test.go

[#182782378](https://www.pivotaltracker.com/story/show/182782378)

test: add postgresql update & upgrade tests

---

acceptance-tests/helpers/brokers/env.go
acceptance-tests/withoutcredhub_test.go

[#182296536](https://www.pivotaltracker.com/story/show/182296536)

test(s3): define plans for "withoutcredhub" and others

---

docs/draft-release-notes.md
terraform/postgresql/provision/main.tf

[#182815511](https://www.pivotaltracker.com/story/show/182815511)

feat: Change admin password length to 64

---

acceptance-tests/helpers/brokers/env.go
acceptance-tests/s3_test.go

[#182296536](https://www.pivotaltracker.com/story/show/182296536)

test(s3): use the proper plan

---

aws-postgresql.yml
docs/configuration.md
docs/draft-release-notes.md
terraform/postgresql/provision/data.tf
terraform/postgresql/provision/main.tf
terraform/postgresql/provision/variables.tf

[#182758527](https://www.pivotaltracker.com/story/show/182758527)

feat: Remove cores property for Postgres

---

acceptance-tests/apps/postgresqlapp/internal/app/app.go
acceptance-tests/apps/postgresqlapp/internal/app/drop_schema.go
acceptance-tests/apps/postgresqlapp/main.go
acceptance-tests/upgrade/update_and_upgrade_postgres_test.go

[#182782378](https://www.pivotaltracker.com/story/show/182782378)
Signed-off-by: Konstantin Semenov <ksemenov@pivotal.io>

test: sync postgres test app with gcp brokerpack

---

integration-tests/postgresql_test.go

[#182758722](https://www.pivotaltracker.com/story/show/182758722)

test(postgresql): add provision property testing

---

acceptance-tests/upgrade/update_and_upgrade_s3_test.go

[#182782378](https://www.pivotaltracker.com/story/show/182782378)
Signed-off-by: Konstantin Semenov <ksemenov@pivotal.io>

test: added label to the s3 acceptance test

---

Makefile

[#182853321](https://www.pivotaltracker.com/story/show/182853321)

chore: remove old make task to push the local broker

---

acceptance-tests/helpers/brokers/create.go
acceptance-tests/helpers/brokers/env.go
acceptance-tests/helpers/brokers/update.go
acceptance-tests/upgrade/update_and_upgrade_postgres_test.go
acceptance-tests/upgrade/update_and_upgrade_s3_test.go

[#182866238](https://www.pivotaltracker.com/story/show/182866238)

test: add old plans through env variables for upgrade tests

---

acceptance-tests/helpers/brokers/create.go
acceptance-tests/withoutcredhub_test.go

[#182866238](https://www.pivotaltracker.com/story/show/182866238)

test: set up env variables in no credhub tests

---

acceptance-tests/helpers/brokers/create.go
acceptance-tests/helpers/brokers/env.go
acceptance-tests/withoutcredhub_test.go

test: fix withoutcredhub tests

---

acceptance-tests/upgrade/update_and_upgrade_s3_test.go

[#182855842](https://www.pivotaltracker.com/story/show/182855842)

test(s3): upgrade test should perform upgrade

---

docs/draft-release-notes.md

[#182758657](https://www.pivotaltracker.com/n/projects/2425126/stories/182758657)
* ~~[] Have you added Draft Release Notes in `docs/draft-release-notes.md`?~~

fix: typo in documentation

---

aws-s3-bucket.yml
integration-tests/s3_test.go

[#182524772](https://www.pivotaltracker.com/story/show/182524772)
* ~~[ ] Have you added Draft Release Notes in `docs/draft-release-notes.md`?~~ update to existing feature

feat(s3): make sure object retention properties can be unset

---

aws-postgresql.yml
docs/draft-release-notes.md
integration-tests/integration_test_suite_test.go
integration-tests/postgresql_test.go
terraform/postgresql/provision/main.tf
terraform/postgresql/provision/variables.tf

[#182816467](https://www.pivotaltracker.com/n/projects/2425126/stories/182816467)

feat: enable encryption with a custom key - PostgreSQL

---

acceptance-tests/dynamodb_test.go
acceptance-tests/helpers/services/create.go
acceptance-tests/helpers/services/update.go
acceptance-tests/mysql_test.go
acceptance-tests/postgresql_test.go
acceptance-tests/redis_test.go
acceptance-tests/s3_test.go
acceptance-tests/upgrade/update_and_upgrade_dynamodb_test.go
acceptance-tests/upgrade/update_and_upgrade_mysql_test.go
acceptance-tests/upgrade/update_and_upgrade_s3_test.go
acceptance-tests/withoutcredhub_test.go

Also made changes to make update and create helpers more similar

test: Add update and upgrade test for mySQL and DynamoDB

---

acceptance-tests/upgrade/update_and_upgrade_dynamodb_test.go
acceptance-tests/upgrade/update_and_upgrade_redis_test.go

test: Add redis upgrade test

---

cf-manifest.yml
dependency-manifest.yml
docs/draft-release-notes.md
manifest.yml
terraform/postgresql/bind/main.tf
terraform/postgresql/bind/outputs.tf
terraform/postgresql/bind/provider.tf

[#182888815](https://www.pivotaltracker.com/story/show/182888815)

fix: delete postgresql user during unbind

---

Makefile
aws-dynamodb.yml
aws-mysql.yml
aws-postgresql.yml
aws-redis-cluster.yml
aws-s3-bucket.yml
docs/draft-release-notes.md
manifest.yml
terraform/dynamodb/bind/provider.tf
terraform/dynamodb/bind/versions.tf
terraform/dynamodb/provision/provider.tf
terraform/dynamodb/provision/versions.tf
terraform/mysql/bind/versions.tf
terraform/mysql/provision/provider.tf
terraform/mysql/provision/versions.tf
terraform/postgresql/bind/versions.tf
terraform/postgresql/provision/main.tf
terraform/postgresql/provision/provider.tf
terraform/postgresql/provision/versions.tf
terraform/redis/cluster/provision/provider.tf
terraform/redis/cluster/provision/versions.tf
terraform/s3/bind/provider.tf
terraform/s3/bind/versions.tf
terraform/s3/provision/data.tf
terraform/s3/provision/provider.tf
terraform/s3/provision/versions.tf

[#181155156](https://www.pivotaltracker.com/story/show/181155156)

feat: add upgrade to Terraform 0.13.7

---

docs/draft-release-notes.md
manifest.yml
terraform/dynamodb/bind/outputs.tf
terraform/dynamodb/provision/outputs.tf
terraform/mysql/bind/outputs.tf
terraform/mysql/provision/outputs.tf
terraform/postgresql/bind/outputs.tf
terraform/postgresql/provision/outputs.tf
terraform/redis/cluster/provision/outputs.tf
terraform/s3/bind/outputs.tf

[#181155156](https://www.pivotaltracker.com/story/show/181155156)

feat: add upgrade to Terraform 1.1.9

---

README.md

Main change it to remove the Go version since it's outdated, and will
likely become outdated again soon enough.
[#182984431](https://www.pivotaltracker.com/story/show/182984431)

chore: tidy up README.md

---

acceptance-tests/apps/postgresqlapp/internal/app/get.go

[#183010759](https://www.pivotaltracker.com/story/show/183010759)

test: improve error message when finding element fails

---

aws-postgresql.yml

chore: Remove default Postgres version

---

aws-postgresql.yml

[#182710173](https://www.pivotaltracker.com/story/show/182710173)

docs(postgres): remove invalid reference to cache_size

---

acceptance-tests/acceptance_tests_suite_test.go
acceptance-tests/apps/postgresqlapp/internal/credentials/credentials.go
acceptance-tests/helpers/dms/aws.go
acceptance-tests/helpers/dms/dms.go
acceptance-tests/helpers/dms/endpoint.go
acceptance-tests/helpers/dms/instance.go
acceptance-tests/helpers/dms/subnet_group.go
acceptance-tests/helpers/dms/task.go
acceptance-tests/helpers/environment/metadata.go
acceptance-tests/helpers/services/create.go
acceptance-tests/postgresql_data_migration_test.go

[#182845517](https://www.pivotaltracker.com/story/show/182845517)

test(postgres): add data migration test

---

aws-s3-bucket.yml
docs/draft-release-notes.md
integration-tests/s3_test.go

[#182286086](https://www.pivotaltracker.com/story/show/182286086)

feat: remove Beta tag for S3

---

Makefile
acceptance-tests/aurora_postgresql_test.go
acceptance-tests/helpers/brokers/env.go
aws-aurora-postgresql.yml
docs/draft-release-notes.md
integration-tests/aurora_postgresql_test.go
integration-tests/integration_test_suite_test.go
manifest.yml
scripts/push-broker.sh
terraform/aurora-postgresql/bind/main.tf
terraform/aurora-postgresql/bind/outputs.tf
terraform/aurora-postgresql/bind/provider.tf
terraform/aurora-postgresql/bind/variables.tf
terraform/aurora-postgresql/bind/versions.tf
terraform/aurora-postgresql/provision/data.tf
terraform/aurora-postgresql/provision/main.tf
terraform/aurora-postgresql/provision/outputs.tf
terraform/aurora-postgresql/provision/provider.tf
terraform/aurora-postgresql/provision/variables.tf
terraform/aurora-postgresql/provision/versions.tf
terraform/postgresql/provision/data.tf

This introduces the foundations of a new Aurora PostgreSQL service that works end to end,
and can have features added to it.
[#183001781](https://www.pivotaltracker.com/story/show/183001781)

feat: Aurora PostgreSQL foundations

---

docs/draft-release-notes.md

docs: Clean up release draft notes

---

aws-mysql.yml
docs/draft-release-notes.md
integration-tests/integration_test_suite_test.go
integration-tests/mysql_test.go

[#183023676](https://www.pivotaltracker.com/story/show/183023676)

feat: allow any MySQL version when creating a plan

---

aws-mysql.yml
integration-tests/mysql_test.go
integration-tests/postgresql_test.go
terraform-tests/mysql_test.go
terraform-tests/postgres_test.go
terraform/mysql/provision/main.tf
terraform/mysql/provision/variables.tf
terraform/postgresql/provision/main.tf

[#183023671](https://www.pivotaltracker.com/story/show/183023671)

feat: enable encryption with a custom key

---

terraform-tests/aurora_postgresql_test.go

[#183510231](https://www.pivotaltracker.com/story/show/183510231)

test: use the right port

---

terraform-tests/mysql_test.go

test: Fix failing test

---

acceptance-tests/apps/mysqlapp/internal/app/app.go
acceptance-tests/apps/mysqlapp/internal/app/get.go
acceptance-tests/apps/mysqlapp/internal/app/set.go
acceptance-tests/apps/mysqlapp/internal/connector/connect.go
acceptance-tests/mysql_test.go

[#183463935](https://www.pivotaltracker.com/story/show/183463935)

test: MySQL app can configure TLS mode

---

manifest.yml
terraform/mysql/bind/main.tf
terraform/mysql/bind/outputs.tf
terraform/mysql/bind/provider.tf
terraform/mysql/bind/versions.tf

[#183510231](https://www.pivotaltracker.com/story/show/183510231)
Signed-off-by: Konstantin Semenov <ksemenov@pivotal.io>
* ~~[] Have you added Release Notes in the docs repositories?~~

feat: integrate the new Terraform MySQL provider

---

aws-aurora-postgresql.yml
integration-tests/aurora_postgresql_test.go
terraform-tests/aurora_postgresql_test.go
terraform/aurora-postgresql/provision/main.tf
terraform/aurora-postgresql/provision/variables.tf

[#183535195](https://www.pivotaltracker.com/story/show/183535195)

feat: aurora-psql- Expose minor and major version upgrade

---

acceptance-tests/mysql_data_migration_test.go

Migration from legacy broker to CSB.
[#183440371](https://www.pivotaltracker.com/story/show/183440371)

test: Add test for MySQL migration

---

acceptance-tests/mysql_data_migration_test.go

Update engine version

---

acceptance-tests/mysql_test.go
acceptance-tests/upgrade/update_and_upgrade_mysql_test.go
aws-mysql.yml
integration-tests/mysql_test.go

[#183023668](https://www.pivotaltracker.com/story/show/183023668)

feat: remove mysql plans

---

terraform/aurora-mysql/provision/data.tf
terraform/aurora-postgresql/provision/data.tf

fix: Fix TF formating

---

acceptance-tests/helpers/brokers/env.go

[#183023668](https://www.pivotaltracker.com/story/show/183023668)

test(upgrade): add mysql plans to latest env

---

terraform/mysql/bind/outputs.tf

feat: JDBC URL requires server certificate verification
[#183601516](https://www.pivotaltracker.com/story/show/183601516)

feat: JDBC URL requires server certificate verification

---

terraform/aurora-postgresql/bind/provider.tf

[#183390984](https://www.pivotaltracker.com/story/show/183390984)

feat: change ssl mode to verify-full

---

acceptance-tests/helpers/dms/task.go

Sometimes replication task might take a while to be deleted. We should wait for that before attempting to delete the endpoints
[#183440371](https://www.pivotaltracker.com/story/show/183440371)

test: Wait for deletion of replication task

---

acceptance-tests/helpers/brokers/env.go
acceptance-tests/upgrade/update_and_upgrade_mysql_test.go

[#183023668](https://www.pivotaltracker.com/story/show/183023668)

test: Add mysql plans to fix upgrade test

---

acceptance-tests/helpers/dms/task.go

test: Fix replication task deletion

---

aws-aurora-mysql.yml
aws-aurora-postgresql.yml
integration-tests/aurora_mysql_test.go
integration-tests/aurora_postgresql_test.go

[#183702197](https://www.pivotaltracker.com/story/show/183702197)

chore: subnet group modification force cluster recreation

---

aws-aurora-mysql.yml
aws-mysql.yml
terraform-tests/aurora_mysql_test.go
terraform/aurora-mysql/provision/main.tf
terraform/aurora-mysql/provision/variables.tf

[#183474202](https://www.pivotaltracker.com/story/show/183474202)

feat: Automated backups for Aurora MySQL

---

aws-aurora-mysql.yml
integration-tests/aurora_mysql_test.go
terraform-tests/aurora_mysql_test.go
terraform/aurora-mysql/provision/main.tf
terraform/aurora-mysql/provision/variables.tf

Deletion protection can be enabled. By default it's disabled.
[#183474180](https://www.pivotaltracker.com/story/show/183474180)

feat: aurora-mysql- Expose deletion protection

---

aws-aurora-mysql.yml
aws-dynamodb.yml
aws-mysql.yml
aws-postgresql.yml
aws-redis-cluster.yml
aws-s3-bucket.yml

[#183701212](https://www.pivotaltracker.com/story/show/183701212)

chore: cleanup manifests

---

aws-aurora-postgresql.yml
integration-tests/aurora_postgresql_test.go
terraform-tests/aurora_postgresql_test.go
terraform/aurora-postgresql/provision/main.tf
terraform/aurora-postgresql/provision/variables.tf

[#183535799](https://www.pivotaltracker.com/story/show/183535799)

feat: Enabling enhanced monitoring Aurora PostgreSQL

---

aws-aurora-mysql.yml
integration-tests/aurora_mysql_test.go
terraform-tests/aurora_mysql_test.go
terraform/aurora-mysql/provision/main.tf
terraform/aurora-mysql/provision/variables.tf

[#183535799](https://www.pivotaltracker.com/story/show/183535799)

feat: Enabling enhanced monitoring Aurora MySQL

---

aws-redis-cluster.yml

[#183701212](https://www.pivotaltracker.com/story/show/183701212)

chore: Set redis plan to match constraints

---

acceptance-tests/aurora_postgresql_test.go

chore: remove focus of acceptance tests

---

aws-mysql.yml
integration-tests/mysql_test.go

[#183440388](https://www.pivotaltracker.com/story/show/183440388)

chore: Set MySQL as GA

---

aws-aurora-postgresql.yml
integration-tests/aurora_postgresql_test.go
terraform-tests/aurora_postgresql_test.go
terraform/aurora-postgresql/provision/main.tf
terraform/aurora-postgresql/provision/variables.tf

[#183535527](https://www.pivotaltracker.com/story/show/183535527)

feat: Enable encryption for Aurora PostgreSQL

---

aws-aurora-mysql.yml
integration-tests/aurora_mysql_test.go
terraform-tests/aurora_mysql_test.go
terraform/aurora-mysql/provision/main.tf
terraform/aurora-mysql/provision/variables.tf

feat: [aurora-mysql] enable database encryption

---

aws-aurora-mysql.yml
aws-aurora-postgresql.yml
integration-tests/aurora_mysql_test.go
integration-tests/aurora_postgresql_test.go

[#183873546](https://www.pivotaltracker.com/story/show/183873546)

fix: wrong constraint for db name AWS Aurora

---

acceptance-tests/aurora_mysql_data_migration_test.go

[#183651929](https://www.pivotaltracker.com/story/show/183651929)
* ~~[ ] Have you added Release Notes in the docs repositories?~~0

chore: remove focus from acceptance tests

---

acceptance-tests/aurora_mysql_data_migration_test.go
aws-aurora-mysql.yml
aws-aurora-postgresql.yml
integration-tests/aurora_mysql_test.go
integration-tests/aurora_postgresql_test.go

[#183652040](https://www.pivotaltracker.com/story/show/183652040)

chore: Set Aurora MySQL and PostgreSQL services as GA

---

terraform-tests/mysql_test.go
terraform-tests/postgres_test.go

* ~[ ] Have you added Release Notes in the docs repositories?~

test: Fix terraform tests false positive

---

acceptance-tests/helpers/brokerpaks/version.go
acceptance-tests/helpers/brokers/create.go
acceptance-tests/helpers/brokers/env.go
acceptance-tests/upgrade/update_and_upgrade_dynamodb_test.go
acceptance-tests/upgrade/update_and_upgrade_mysql_test.go
acceptance-tests/upgrade/update_and_upgrade_postgres_test.go
acceptance-tests/upgrade/update_and_upgrade_redis_test.go
acceptance-tests/upgrade/update_and_upgrade_s3_test.go
acceptance-tests/upgrade/upgrade_suite_test.go

[#183813609](https://www.pivotaltracker.com/story/show/183813609)
* ~[ ] Have you added Release Notes in the docs repositories?~

test: Additional configuration for jump upgrades

---

cf-manifest.yml

This reverts commit b358390146c515f4e6f75235477561c0276dea84.
This needs changes to our pool as well. Will investigate further before making this change

Revert "chore: Increase cf manifest disk quota (#734)"

---

acceptance-tests/helpers/apps/prebuild.go

[#184403273](https://www.pivotaltracker.com/story/show/184403273)

chore: add flag to compile test apps without CGO

---

integration-tests/redis_test.go

[#184305581](https://www.pivotaltracker.com/story/show/184305581)

test: AWS Redis - Integration tests

---

terraform-tests/redis_test.go
terraform/redis/cluster/provision/main.tf

[#184464209](https://www.pivotaltracker.com/story/show/184464209)

feat: redis - set apply_immediately to true

---

.envrc
acceptance-tests/helpers/brokers/env.go
aws-redis-cluster.yml
integration-tests/redis_test.go

[#184464183](https://www.pivotaltracker.com/story/show/184464183)

feat: [Redis] make redis_version a user input

---

aws-redis.yml
integration-tests/redis_test.go
terraform-tests/redis_test.go
terraform/redis/cluster/provision/main.tf
terraform/redis/cluster/provision/variables.tf

[#184531450](https://www.pivotaltracker.com/story/show/184531450)

feat(redis): add property backup_name

---

aws-redis.yml
integration-tests/redis_test.go
terraform-tests/redis_test.go
terraform/redis/cluster/provision/data.tf
terraform/redis/cluster/provision/main.tf
terraform/redis/cluster/provision/variables.tf

[#184630004](https://www.pivotaltracker.com/story/show/184630004)

feat(redis): ability to set backup window

---

.gitignore
acceptance-tests/apps/dynamodbnsapp/go.mod
acceptance-tests/apps/dynamodbnsapp/internal/app/app.go
acceptance-tests/apps/dynamodbnsapp/internal/app/middleware.go
acceptance-tests/apps/dynamodbnsapp/internal/app/response.go
acceptance-tests/apps/dynamodbnsapp/internal/app/tables.go
acceptance-tests/apps/dynamodbnsapp/internal/app/values.go
acceptance-tests/apps/dynamodbnsapp/internal/credentials/credentials.go
acceptance-tests/apps/dynamodbnsapp/main.go
acceptance-tests/apps/dynamodbtableapp/internal/app/app.go
acceptance-tests/apps/dynamodbtableapp/internal/app/get.go
acceptance-tests/apps/dynamodbtableapp/internal/app/set.go
acceptance-tests/dynamodb_namespace_test.go
acceptance-tests/helpers/apps/http.go
acceptance-tests/helpers/apps/testapps.go
aws-dynamodb-namespace.yml
terraform-tests/dynamodb_namespace_test.go
terraform-tests/terraform_tests_suite_test.go
terraform/dynamodb-namespace/bind/data.tf
terraform/dynamodb-namespace/bind/main.tf
terraform/dynamodb-namespace/bind/outputs.tf
terraform/dynamodb-namespace/bind/provider.tf
terraform/dynamodb-namespace/bind/variables.tf

[#184673468](https://www.pivotaltracker.com/story/show/184673468)

feat: [DynamoDB-NS] Create binding

---

aws-redis.yml
integration-tests/redis_test.go

[#184654002](https://www.pivotaltracker.com/story/show/184654002)

feat(redis): no longer beta

---

aws-redis.yml

[#184614709](https://www.pivotaltracker.com/story/show/184614709)

docs(redis): immutable node_count if preferred_az set

---

acceptance-tests/aurora_mysql_data_migration_test.go
acceptance-tests/aurora_mysql_test.go
acceptance-tests/aurora_postgresql_test.go
acceptance-tests/dynamodb_namespace_test.go
acceptance-tests/dynamodb_table_test.go
acceptance-tests/helpers/apps/http.go
acceptance-tests/helpers/apps/payload.go
acceptance-tests/helpers/apps/push.go
acceptance-tests/helpers/cf/start.go
acceptance-tests/mysql_data_migration_test.go
acceptance-tests/mysql_test.go
acceptance-tests/postgresql_data_migration_test.go
acceptance-tests/postgresql_test.go
acceptance-tests/redis_test.go
acceptance-tests/s3_migration_test.go
acceptance-tests/s3_test.go
acceptance-tests/upgrade/update_and_upgrade_dynamodb_table_test.go
acceptance-tests/upgrade/update_and_upgrade_mysql_test.go
acceptance-tests/upgrade/update_and_upgrade_postgresql_test.go
acceptance-tests/upgrade/update_and_upgrade_redis_test.go
acceptance-tests/upgrade/update_and_upgrade_s3_test.go
acceptance-tests/withoutcredhub_test.go

[#184673945](https://www.pivotaltracker.com/story/show/184673945)

test: remove duplicated boilerplate JSON parsing

---

aws-dynamodb-table.yml
aws-mysql.yml
aws-postgresql.yml

[#184710879](https://www.pivotaltracker.com/story/show/184710879)

chore: add some missing types and default values

---

acceptance-tests/aurora_postgresql_test.go

test(aurora): remove tls bits check as we are using default aws config

---

Makefile
custom.tfrc.template

[#184673864](https://www.pivotaltracker.com/story/show/184673864)
* ~[ ] Have you added Release Notes in the docs repositories?~

fix: terraform provider location for testing

---

Makefile
aws-redis.yml
custom.tfrc.template
integration-tests/redis_test.go

[#184867642](https://www.pivotaltracker.com/story/show/184867642)
* ~~[] Have you added Release Notes in the docs repositories?~~

fix: [Redis] incorrect values in service properties

---

providers/terraform-provider-csbdynamodbns/Makefile

[#184673864](https://www.pivotaltracker.com/story/show/184673864)
* ~[ ] Have you added Release Notes in the docs repositories?~

fix: tf provider Makefile to use containerized go

---

terraform-tests/aurora_mysql_test.go
terraform-tests/aurora_postgresql_test.go
terraform/aurora-mysql/provision/main.tf
terraform/aurora-postgresql/provision/main.tf

[#184888948](https://www.pivotaltracker.com/story/show/184888948)

fix: apply immediately to avoid inconsistencies in the provider

---

acceptance-tests/upgrade/update_and_upgrade_dynamodb_table_test.go
acceptance-tests/upgrade/update_and_upgrade_redis_test.go

[#184915588](https://www.pivotaltracker.com/story/show/184915588)

test: change acceptance tests after release

---

Makefile
providers/terraform-provider-csbdynamodbns/Makefile

chore: Add make target to compute code coverage

---

aws-aurora-mysql.yml
aws-aurora-postgresql.yml
aws-dynamodb-namespace.yml
aws-dynamodb-table.yml
aws-mysql.yml
aws-postgresql.yml
aws-s3-bucket.yml
integration-tests/aurora_mysql_test.go
integration-tests/aurora_postgresql_test.go
integration-tests/dynamodb_namespace_test.go
integration-tests/dynamodb_table_test.go
integration-tests/integration_test_suite_test.go
integration-tests/mssql_test.go
integration-tests/mysql_test.go
integration-tests/postgresql_test.go
integration-tests/redis_test.go
integration-tests/s3_test.go

[#185158428](https://www.pivotaltracker.com/story/show/185158428)

feat: generic link in service offerings

---

aws-mysql.yml
aws-postgresql.yml
terraform-tests/mysql_test.go
terraform-tests/postgres_test.go
terraform/mysql/provision/data.tf
terraform/mysql/provision/main.tf
terraform/postgresql/provision/data.tf
terraform/postgresql/provision/main.tf

[#185275800](https://www.pivotaltracker.com/story/show/185275800)

feat: [AWS RDS] support setting iops for gp3 storage type

---

manifest.yml

[#185574571](https://www.pivotaltracker.com/story/show/185574571)

fix: remove unused provider

---

manifest.yml

[#185614327](https://www.pivotaltracker.com/story/show/185614327)

chore: upgrade aws provider to latest

---

aws-redis.yml
integration-tests/redis_test.go
terraform-tests/redis_test.go
terraform/redis/cluster/provision/data.tf
terraform/redis/cluster/provision/main.tf
terraform/redis/cluster/provision/variables.tf

[#185574741](https://www.pivotaltracker.com/story/show/185574741)

feat: Enable auto minor version upgrade for Redis

---

terraform-tests/aurora_postgresql_test.go

[#185574620](https://www.pivotaltracker.com/story/show/185574620)

fix: incorrect engine version

---

terraform-tests/aurora_postgresql_test.go

The deleted assertions are already well tested in other tests.
[#185574620](https://www.pivotaltracker.com/story/show/185574620)

test: delete uneccesary test

---

aws-aurora-mysql.yml
aws-aurora-postgresql.yml
aws-mysql.yml
aws-postgresql.yml

[#185677879](https://www.pivotaltracker.com/story/show/185677879)

docs: a major version is mandatory when auto minor version is enabled

---

acceptance-tests/helpers/apps/app.go
acceptance-tests/helpers/apps/push.go
acceptance-tests/helpers/apps/testapps.go

[#185528524](https://www.pivotaltracker.com/story/show/185528524)

test: limit disk used by test apps

---

acceptance-tests/upgrade/update_and_upgrade_postgresql_test.go

test: use major version when upgrade postgres

---

acceptance-tests/mssql_test.go
aws-mssql.yml
integration-tests/mssql_test.go
terraform-tests/mssql_test.go
terraform/mssql/provision/main.tf
terraform/mssql/provision/variables.tf

feat: [MSSQL] expose deletion_protection property

---

terraform/mssql/provision/outputs.tf

fix: status message with incorrect link

---

terraform-tests/mssql_test.go

test: TF test failing when invalid engine version

---

aws-mssql.yml
integration-tests/mssql_test.go
terraform/mssql/provision/main.tf
terraform/mssql/provision/variables.tf

[#185201189](https://www.pivotaltracker.com/story/show/185201189)
- https://github.com/pivotal-cf/docs-csb-aws/commit/4d4ef2365b7ba4738952e8ea54d7e86bdf2c3934

feat: [MSSQL] expose option_group_name

---

Makefile

fix: ci shell masking errors #185955999

---

aws-mssql.yml
integration-tests/mssql_test.go
terraform-tests/mssql_test.go
terraform/mssql/provision/main.tf
terraform/mssql/provision/variables.tf

[#185202023](https://www.pivotaltracker.com/story/show/185202023)
Related PRs: https://github.com/pivotal-cf/docs-csb-aws/pull/300

feat: [MSSQL] expose performance insights

---

aws-mssql.yml
integration-tests/mssql_test.go
terraform-tests/mssql_test.go
terraform/mssql/provision/main.tf
terraform/mssql/provision/variables.tf

[#185201378](https://www.pivotaltracker.com/story/show/185201378)
Related PRs:
- https://github.com/pivotal-cf/docs-csb-aws/pull/301

feat: [MSSQL] expose character_set_name

---

acceptance-tests/apps/jdbctestapp/manifest-sqlserver.yml
acceptance-tests/apps/mssqlapp/internal/app/app.go
acceptance-tests/apps/mssqlapp/internal/app/create_schema.go
acceptance-tests/apps/mssqlapp/internal/app/drop_schema.go
acceptance-tests/apps/mssqlapp/internal/app/fill_db.go
acceptance-tests/apps/mssqlapp/internal/app/get.go
acceptance-tests/apps/mssqlapp/internal/app/set.go
acceptance-tests/apps/mssqlapp/internal/credentials/connector.go
acceptance-tests/apps/mssqlapp/internal/credentials/credentials.go
acceptance-tests/apps/mssqlapp/internal/credentials/url_encoder.go
acceptance-tests/apps/mssqlapp/main.go
acceptance-tests/helpers/apps/testapps.go
acceptance-tests/helpers/jdbcapp/jdbcapp.go
acceptance-tests/mssql_test.go
aws-mssql.yml
integration-tests/mssql_test.go
providers/terraform-provider-csbsqlserver/connector/url_encoder.go
providers/terraform-provider-csbsqlserver/connector/url_encoder_test.go
terraform-tests/mssql_test.go
terraform/mssql/bind/data.tf
terraform/mssql/bind/outputs.tf
terraform/mssql/bind/provider.tf
terraform/mssql/bind/variables.tf
terraform/mssql/provision/main.tf
terraform/mssql/provision/outputs.tf
terraform/mssql/provision/variables.tf

feat: [MSSQL] force ssl connections by default

---

terraform-tests/mssql_test.go

test: fix require ssl Terraform test

---

aws-mssql.yml
integration-tests/mssql_test.go
terraform-tests/helpers/resource_changes.go
terraform-tests/mssql_test.go
terraform/mssql/provision/main.tf
terraform/mssql/provision/variables.tf

[#185201446](https://www.pivotaltracker.com/story/show/185201446)
Related PRs:
- https://github.com/pivotal-cf/docs-csb-aws/pull/302

feat: [MSSQL] expose multi_az

---

acceptance-tests/mssql_test.go

[#185202654](https://www.pivotaltracker.com/story/show/185202654)

fix: use default values because multiaz needs backups

---

acceptance-tests/apps/postgresqlapp/internal/app/create_schema.go
acceptance-tests/apps/postgresqlapp/internal/app/drop_schema.go
acceptance-tests/apps/postgresqlapp/internal/app/set.go

[#185844429](https://www.pivotaltracker.com/story/show/185844429)

fix: incorrect log

---

aws-mssql.yml
integration-tests/mssql_test.go
terraform-tests/mssql_test.go
terraform/mssql/provision/data.tf
terraform/mssql/provision/main.tf
terraform/mssql/provision/variables.tf

Two log groups exported: agent and error.
[#185202654](https://www.pivotaltracker.com/story/show/185202654)

feat: [MSSQL] minimum implementation CloudWatch

---

acceptance-tests/mssql_test.go
terraform/mssql/bind/data.tf

[#185844429](https://www.pivotaltracker.com/story/show/185844429)

fix: [MSSQL] JDBC disable is not a valid option

---

acceptance-tests/mssql_test.go

fix: use a general message in TLS assertion

---

aws-mssql.yml
integration-tests/mssql_test.go

[#185202513](https://www.pivotaltracker.com/story/show/185202513)

feat: [MSSQL] set service as GA

---

aws-mssql.yml
integration-tests/mssql_test.go

fix: uppercases are not allowed

---

docs/installation.md

[#186141323](https://www.pivotaltracker.com/story/show/186141323)

fix: add necessary permission for creating egress rules

---

aws-mssql.yml
integration-tests/mssql_test.go
terraform-tests/mssql_test.go

[#186141844](https://www.pivotaltracker.com/story/show/186141844)

chore: [MSSQL]  iops should default to 1000

---

aws-mssql.yml
aws-mysql.yml
aws-postgresql.yml

[#186140236](https://www.pivotaltracker.com/story/show/186140236)

feat: remove RDS storage size maximum constraint

---

Makefile
providers/terraform-provider-csbsqlserver/connector/connector.go
providers/terraform-provider-csbsqlserver/csbsqlserver/binding_resource_test.go

The provider will be used in several service providers and these checks are for AWS only.
They are not required.
[#185100152](https://www.pivotaltracker.com/story/show/185100152)

fix: synchronise common functionality providers

---

acceptance-tests/upgrade/update_and_upgrade_mssql_test.go

[#185202616](https://www.pivotaltracker.com/story/show/185202616)

test: [MSSQL] upgrade test

---

manifest.yml

[#186276385](https://www.pivotaltracker.com/story/show/186276385)

fix: correct manifest property definition

---

Makefile
terraform-tests/aurora_mysql_test.go
terraform-tests/aurora_postgresql_test.go
terraform-tests/mssql_test.go
terraform-tests/mysql_test.go
terraform-tests/postgres_test.go
terraform-tests/redis_test.go
terraform-tests/s3_test.go

[#186442352](https://www.pivotaltracker.com/story/show/186442352)

chore: allow filtering terraform-tests based on region

---

acceptance-tests/mssql_data_migration_test.go

chore: enforce DBInstanceClass supported by GovCloud

---

terraform-tests/terraform_tests_suite_test.go

chore: allow passing different VPC to fix tests in GovCloud

---

terraform-tests/terraform_tests_suite_test.go

chore: fix govcloud terraform tests 2 #186311950

---

terraform-tests/aurora_mysql_test.go
terraform-tests/aurora_postgresql_test.go
terraform-tests/mssql_test.go
terraform-tests/mysql_test.go
terraform-tests/postgres_test.go
terraform-tests/redis_test.go
terraform-tests/s3_test.go

Related commits:
- https://github.com/pivotal/cloud-service-broker-ci/commit/de57c1a527358de11da7f8f9d424a519104181eb

chore: apply @blgm suggestions regarding GovCloud

---

acceptance-tests/upgrade/update_and_upgrade_redis_test.go

chore: replace node_type unsupported in GovCloud

---

terraform-tests/redis_test.go

For more information:
https://github.com/hashicorp/terraform-provider-aws/issues/11524

chore: fix terraform-tests to account for new property

---

terraform/mysql/bind/versions.tf
terraform/postgresql/bind/versions.tf

[#186588913](https://www.pivotaltracker.com/story/show/186588913)

fix: remove obsolete mysql and postgres providers from versions file

---

acceptance-tests/upgrade/update_and_upgrade_aurora_postgresql_test.go

[#186680739](https://www.pivotaltracker.com/story/show/186680739)

chore: fix ci to workaround major upgrade test errors

---

acceptance-tests/upgrade/update_and_upgrade_aurora_postgresql_test.go

fix: test trying to downgrade

---

acceptance-tests/upgrade/update_and_upgrade_aurora_postgresql_test.go

chore: make test brokerpak upgrade green

---

acceptance-tests/helpers/apps/testapps.go
acceptance-tests/sqs_test.go

[#186787985](https://www.pivotaltracker.com/story/show/186787985)

test: SQS send and receive acceptance test

---

acceptance-tests/sqs_test.go

[#186769595](https://www.pivotaltracker.com/story/show/186769595)

test: Change test to check the FIFO queue

---

aws-sqs.yml
integration-tests/sqs_test.go

~~* [ ] Have you ran acceptance tests for the service under change?~~

feat: change SQS description to clearly state Beta

---

acceptance-tests/apps/sqsapp/internal/app/send.go
acceptance-tests/sqs_test.go

test: Added FIFO queue acceptance test

---

acceptance-tests/sqs_test.go

test: Remove acciddental test focus

---

.gitignore

chore: delete unnecessary test binary

---

.github/dependabot.yml

chore: Temporarly ignore any updates of the CSB while we migrate to using OpenTofu

---

acceptance-tests/sqs_test.go
acceptance-tests/upgrade/update_and_upgrade_sqs_test.go

Adds the standard upgrade test to ensure that SQS continues to work through an upgrade and subsequent update.

test: upgrade of SQS

---

aws-sqs.yml
integration-tests/sqs_test.go

[#187103958](https://www.pivotaltracker.com/story/show/187103958)

feat: SQS ready for general availability

---

.github/dependabot.yml
.github/labeler.yml
.github/release.yml

chore: Rely on dependabot to label PRs

---

terraform-tests/helpers/terraform.go

[#187199931](https://www.pivotaltracker.com/story/show/187199931)

test: rename method to not mention terraform

---

docs/installation.md

[#187060784](https://www.pivotaltracker.com/story/show/187060784)

docs: Amazon SQS service requires new permissions

---

providers/terraform-provider-csbdynamodbns/go.mod
providers/terraform-provider-csbdynamodbns/go.sum
providers/terraform-provider-csbmajorengineversion/go.mod
providers/terraform-provider-csbmajorengineversion/go.sum

[#187369827](https://www.pivotaltracker.com/story/show/187369827)

fix: vulnerability GO-2024-2687 in providers

---

aws-dynamodb-table.yml
terraform/dynamodb-table/provision/variables.tf

[#185758439](https://www.pivotaltracker.com/story/show/185758439)

chore: remove unused instance_name from dynamodb-table

---

manifest.yml

feat: Update tofu to latest v1.7.2

---

manifest.yml

feat: Update tofu to latest v1.8.0

---

acceptance-tests/s3withvpcendpoint_test.go

[#187876023](https://www.pivotaltracker.com/story/show/187876023)

test: the error message does not add much value and changes too often

---

terraform-tests/mysql_test.go

test: Fix setup for terraform test to include admin_username

---

terraform-tests/aurora_mysql_test.go

test: fix admin password aurora mysql test

---

terraform-tests/aurora_mysql_test.go

test: fix Aurora mysql  terraform test

---

terraform-tests/mssql_test.go

By adding a creation timestamp to resources created by a test, we can manage those resource better and detect any leaked resources.

test: tag test resources with creation timestamp

---

acceptance-tests/helpers/awscli/aws.go
acceptance-tests/mssql_test.go
acceptance-tests/mysql_test.go
acceptance-tests/postgresql_test.go

- Needed to restore DB to correct VPC and subnet
- Also improved logging to be less verbose
- Also switched to using Go test app as it have better error reporting than the Java one

test: fix MS-SQL restore test

---

acceptance-tests/aurora_postgresql_test.go

chore: added test case for testing the latest version of Aurora PG supported by AGC.

---

acceptance-tests/aurora_postgresql_test.go

chore: Update tests to test with aurora pg 17
